name = "FEM"
uuid = "98513c08-06cb-4a10-8140-30301e6c2e54"
authors = ["Sun Haohang <sunhh.hhu@gmail.com>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
JLD2 = "0.4.51"
JuMP = "1.25.0"
PATHSolver = "1.7.8"
Roots = "2.1.6"
ScatteredInterpolation = "0.3.6"
StaticArrays = "1.9.7"
